### ISSUE TITLE
Gnome 3.24 compatibility

### ISSUE THREAD

**Issue by t0phr** [0xhjohnson/arc-theme-gotham#1]
Great theme, some minor issues after upgrade to Gnome 3.24, e.g.:
 - Weather area in topbar date menu
 - Missing selected day indicator in calendar in topbar date menu

In the original arc theme these issues are already fixed, maybe not much work needed on your side.

**Comment by 0xhjohnson** [comment]
I just issued a [commit](https://github.com/hjohnson02/arc-theme-gotham/commit/a98669e1552f4618a51d5f885bf2cf4dd53592e8) that should have fixed everything. I don't have a way of testing currently as my linux machine is at my other place so let me know if there are any other issues.

**Comment by t0phr** [comment]
Looks fine, thanks! 👍
